apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-ingress
  namespace: "{{ .Values.global.namespace }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /ecom(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: user-svc
            port:
              number: 8000
