apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: {{ .Values.global.namespace }}
data: 
  POSTGRES_PASSWORD: postgres