apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ecom-app.db.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   {{- include "ecom-app.db.selectorLabels" . | nindent 4 }}